service: dynamodbPedido

frameworkVersion: '2'

variablesResolutionMode: 20210219

package:
  exclude:
    - node_modules/aws-sdk/**
    - mocks/**
    - variaveis.exemplo.js
    - package-lock.json

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  apiGateway:
    shouldStartNameWithService: true
  region: sa-east-1
  environment:
    TABELA_PEDIDO: Pedido
  iam:
    role:
      statements:
      - Effect: Allow
        Action:
          - dynamodb:Scan
          - dynamodb:Query
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
        Resource: "arn:aws:dynamodb:${self:provider.region}:*:*"

functions:
  adicionar_pedido:
    handler: src/handler.adicionar
    events:
      - http:
          path: pedido
          method: post
          cors: true
  listar_pedido:
    handler: src/handler.listar
    events:
      - http:
          path: pedido
          method: get
          cors: true
  buscar_pedido:
    handler: src/handler.buscar
    events:
      - http:
          path: pedido/{id}
          method: get
          cors: true
  atualizar_pedido:
    handler: src/handler.atualizar
    events:
      - http:
          path: pedido/{id}
          method: put
          cors: true
  deletar_pedido:
    handler: src/handler.deletar
    events:
      - http:
          path: pedido/{id}
          method: delete
          cors: true

resources:
  Resources:
    Produto:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:provider.environment.TABELA_PEDIDO}
        AttributeDefinitions:
          -
            AttributeName: numero_pedido
            AttributeType: S
        KeySchema:
          -
            AttributeName: numero_pedido
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1