service: dynamodbPedido

frameworkVersion: '2'

variablesResolutionMode: 20210219

package:
  exclude:
    - node_modules/aws-sdk/**
    - mocks/**
    - variaveis.exemplo.js
    - package-lock.json

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  apiGateway:
    shouldStartNameWithService: true
  region: sa-east-1
  environment:
    nomeTabela: Pedido
  iam:
    role:
      statements:
      - Effect: Allow
        Action:
          - dynamodb:Scan
          - dynamodb:Query
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
        Resource: "arn:aws:dynamodb:${self:provider.region}:*:*"

functions:
  adicionarPedido:
    handler: src/handler.adicionar
    events:
      - http:
          path: pedido
          method: post
          cors: true
  listarPedido:
    handler: src/handler.listar
    events:
      - http:
          path: pedidos/{idUsuario}
          method: get
          cors: true
  buscarPedido:
    handler: src/handler.buscar
    events:
      - http:
          path: pedido/{numeroPedido}
          method: get
          cors: true
  atualizarPedido:
    handler: src/handler.atualizar
    events:
      - http:
          path: pedido/{numeroPedido}
          method: put
          cors: true
  deletarPedido:
    handler: src/handler.deletar
    events:
      - http:
          path: pedido/{numeroPedido}
          method: delete
          cors: true

resources:
  Resources:
    Pedido:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:provider.environment.nomeTabela}
        AttributeDefinitions:
          -
            AttributeName: numeroPedido
            AttributeType: S
        KeySchema:
          -
            AttributeName: numeroPedido
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1