service: dynamodbProduto

frameworkVersion: '2'

variablesResolutionMode: 20210219

# plugins:
#   - serverless-dotenv-plugin # usa o 'environment' como arquivo '.env', permite o uso do 'process.env.'
#   - serverless-bundle # Package our functions with Webpack
#   - serverless-offline # lambda, api gateway offline
#   - serverless-dynamodb-local
#   - serverless-s3-local

package:
  # individually: true
  exclude:
    - node_modules/aws-sdk/**
    - mocks/**
    - package-lock.json

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  environment:
    nomeTabela: Produto
    nomeBucket: produto-upload
  apiGateway:
    shouldStartNameWithService: true
  region: sa-east-1
  iam:
    role:
      statements:
      - Effect: Allow
        Action:
          - s3:PutObject
          - s3:PutObjectAcl
          - s3:GetObject
          - s3:DeleteObject
        Resource: "arn:aws:s3:::${self:provider.environment.nomeBucket}/*"
      - Effect: Allow
        Action:
          - dynamodb:Scan
          - dynamodb:Query
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
          - dynamodb:DescribeTable
        Resource: "arn:aws:dynamodb:${self:provider.region}:*:*"

functions:
  adicionar_produto:
    handler: src/handler.adicionar
    events:
      - http:
          path: produto
          method: post
          cors: true
  atualizar_produto:
    handler: src/handler.atualizar
    events:
      - http:
          path: produto/{id}
          method: put
          cors: true
  deletar_produto:
    handler: src/handler.deletar
    events:
      - http:
          path: produto/{id}
          method: delete
          cors: true
  buscar_produto:
    handler: src/handler.buscar
    events:
      - http:
          path: produto/{id}
          method: get
          cors: true
  listar_produto:
    handler: src/handler.listar
    events:
      - http:
          path: produto
          method: get
          cors: true

resources:
  Resources:
    S3Bucket:
      Type: 'AWS::S3::Bucket'
      # DeletionPolicy: Retain
      Properties:
        BucketName: ${self:provider.environment.nomeBucket}
    Produto:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:provider.environment.nomeTabela}
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1