service: bgc-backend-serverless

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: sa-east-1
  apiGateway:
    shouldStartNameWithService: true
  iam:
    role:
      statements:
      - Effect: Allow
        Action:
          - ses:SendEmail
          - ses:SendRawEmail
        Resource: "*"

functions:
  enviarEmail:
    handler: handler.enviarEmail
    events:
      - http:
          path: email
          method: post
          cors: true
  # listarProduto:
  #   handler: ${self:provider.environment.HANDLER_PRODUTO}Listar.listar
  #   events:
  #     - http:
  #         path: /
  #         method: get
  #         cors: true
  # buscarProduto:
  #   handler: ${self:provider.environment.HANDLER_PRODUTO}Buscar.buscar
  #   events:
  #     - http:
  #         path: produto/{id}
  #         method: get
  #         cors: true